### ISSUE TITLE
Problem with some background icons

### ISSUE THREAD

**Issue by thomas-gt** [hkraji/weather-widget#3]
Hi,
Thanks for this widget.
I get some problems with large background icons which go outside widget like sun at the bottom (see capture). Some others (eg cloud) are OK are smaller.
Background for other widgets seem OK (see capture).
Unsure which css file to modify to fix this issue.
Thx
Tom
![weather1](https://cloud.githubusercontent.com/assets/6240609/20449819/0951f672-adec-11e6-95bd-a6309c92dd7c.png)

**Comment by thiemok** [comment]
just add something like `.icon-background {
    margin-top: 50px;
  }` into weather.scss inside the brackets of `.widget-weather{...}`

**Comment by thomas-gt** [comment]
Thanks !
